<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Shadow" failures="2" tests="2" name="TravelInsuranceDetailsTest" time="6.386" errors="0" timestamp="2021-06-29T16:44:20 IST">
  <testcase classname="testcases.TravelInsuranceDetailsTest" name="homePageTitle" time="5.829">
    <failure type="java.lang.AssertionError" message="expected [Travel Insurance: Buy Online with Covid-19 Coverage] but found [Travel Insurance: Buy Travel Insurance Online with Covid-19 Coverage]">
      <![CDATA[java.lang.AssertionError: expected [Travel Insurance: Buy Online with Covid-19 Coverage] but found [Travel Insurance: Buy Travel Insurance Online with Covid-19 Coverage]
at testcases.TravelInsuranceDetailsTest.homePageTitle(TravelInsuranceDetailsTest.java:51)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- homePageTitle -->
  <testcase classname="testcases.TravelInsuranceDetailsTest" name="checkExcelData" time="0.0">
    <failure type="org.testng.TestNGException" message="
Data Provider public java.lang.Object[] testcases.TravelInsuranceDetailsTest.dp() throws java.io.IOException returned a null value">
      <![CDATA[org.testng.TestNGException: 
Data Provider public java.lang.Object[] testcases.TravelInsuranceDetailsTest.dp() throws java.io.IOException returned a null value
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- checkExcelData -->
</testsuite> <!-- TravelInsuranceDetailsTest -->
